### ISSUE TITLE
panel，vue项目

### ISSUE THREAD

**Issue by Hzzzhhhhhhh** [youdeyunke/app#1]
npm WARN vue-awesome-swiper@4.1.1 requires a peer of swiper@^5.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN vue-echarts@6.7.3 requires a peer of vue@^2.6.12 || ^3.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-vue@5.2.3 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN vue-eslint-parser@5.0.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN babel-plugin-polyfill-corejs3@0.10.6 requires a peer of @babel/core@^7.4.0 || ^8.0.0-0 <8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN babel-plugin-polyfill-corejs2@0.4.12 requires a peer of @babel/core@^7.4.0 || ^8.0.0-0 <8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN babel-plugin-polyfill-regenerator@0.6.3 requires a peer of @babel/core@^7.4.0 || ^8.0.0-0 <8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/helper-define-polyfill-provider@0.6.3 requires a peer of @babel/core@^7.4.0 || ^8.0.0-0 <8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN vue-admin-template@4.2.1 No repository field.

npm ERR! code EPERM
npm ERR! syscall rename
npm ERR! path D:\idea_code\xmsy\ershoufang\fangchan-master\panel\node_modules\cnpm\node_modules\.npm.DELETE\node_modules\@colors
npm ERR! dest D:\idea_code\xmsy\ershoufang\fangchan-master\panel\node_modules\cnpm\node_modules\npm\node_modules\@colors
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, rename 'D:\idea_code\xmsy\ershoufang\fangchan-master\panel\node_modules\cnpm\node_modules\.npm.DELETE\node_modules\@colors' -> 'D:\idea_code\xmsy\ershoufang\fangchan-master\panel\node_modules\cnpm\node_modules\npm\node_modules\@colors'
npm ERR!  [OperationalError: EPERM: operation not permitted, rename 'D:\idea_code\xmsy\ershoufang\fangchan-master\panel\node_modules\cnpm\node_

PS D:\idea_code\xmsy\ershoufang\fangchan-master\panel> npm install

你好，我在这个panel项目里面npm install，但是一直下载不了，显示错误，但是node版本已经换成v14.18.1了

[2024-12-05T08_42_34_427Z-debug.log](https://github.com/user-attachments/files/18020299/2024-12-05T08_42_34_427Z-debug.log)

**Comment by YOHN89** [comment]
operation not permitted 是权限错误，你用管理员身份启动power shell 之后再重新运行命令再试

**Comment by Hzzzhhhhhhh** [comment]
> operation not allowed 是权限错误，你用管理员身份启动power shell 之后再重新运行命令再试

是用管理员身份运行的，然后报这个错误

**Comment by YOHN89** [comment]
把`node_modules `删掉后再试一下

**Comment by Hzzzhhhhhhh** [comment]
> 把删掉后再试一下`node_modules `

这个我也试过了，
刚刚我到网上找到说要指定cnpm版本，npm install cnpm@7.1.0 -g，咱们这个项目cnpm版本是什么呀

**Comment by YOHN89** [comment]
不需要cnpm， 我们这里在windows机器上测试npm install 可以正常安装，npm run dev 可以正常启动项目，没有这个报错。

检查一下你的nodejs环境配置，这个问题与项目本身代码没有关联。

**Comment by Hzzzhhhhhhh** [comment]
> 不需要cnpm， 我们这里在windows机器上测试npm install可以正常安装，npm run dev 可以正常启动项目，没有这个报错。
> 
> 检查一下你的nodejs环境配置，这个问题与项目本身代码没有关联。

试了四个电脑，都是上面那个rename的问题报错，请问一下测试nodejs的配置环境搭建是nvm多版本node控制吗，还是仅安装了一个node14.18.1版本。
nvm控制多版本node不影响这个项目的install吧？但是都报错了，也没遇见过这样子的问题

**Comment by udyk-dev** [comment]
一般都是因为操作系统的环境差异导致的问题，你最好用docker跑
